// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cache

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTranscoder creates a new instance of MockTranscoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranscoder[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranscoder[T] {
	mock := &MockTranscoder[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTranscoder is an autogenerated mock type for the Transcoder type
type MockTranscoder[T any] struct {
	mock.Mock
}

type MockTranscoder_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockTranscoder[T]) EXPECT() *MockTranscoder_Expecter[T] {
	return &MockTranscoder_Expecter[T]{mock: &_m.Mock}
}

// Decode provides a mock function for the type MockTranscoder
func (_mock *MockTranscoder[T]) Decode(s string) (T, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (T, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) T); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTranscoder_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockTranscoder_Decode_Call[T any] struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - s string
func (_e *MockTranscoder_Expecter[T]) Decode(s interface{}) *MockTranscoder_Decode_Call[T] {
	return &MockTranscoder_Decode_Call[T]{Call: _e.mock.On("Decode", s)}
}

func (_c *MockTranscoder_Decode_Call[T]) Run(run func(s string)) *MockTranscoder_Decode_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTranscoder_Decode_Call[T]) Return(v T, err error) *MockTranscoder_Decode_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockTranscoder_Decode_Call[T]) RunAndReturn(run func(s string) (T, error)) *MockTranscoder_Decode_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Encode provides a mock function for the type MockTranscoder
func (_mock *MockTranscoder[T]) Encode(v T) (string, error) {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(T) (string, error)); ok {
		return returnFunc(v)
	}
	if returnFunc, ok := ret.Get(0).(func(T) string); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(T) error); ok {
		r1 = returnFunc(v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTranscoder_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type MockTranscoder_Encode_Call[T any] struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - v T
func (_e *MockTranscoder_Expecter[T]) Encode(v interface{}) *MockTranscoder_Encode_Call[T] {
	return &MockTranscoder_Encode_Call[T]{Call: _e.mock.On("Encode", v)}
}

func (_c *MockTranscoder_Encode_Call[T]) Run(run func(v T)) *MockTranscoder_Encode_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTranscoder_Encode_Call[T]) Return(s string, err error) *MockTranscoder_Encode_Call[T] {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTranscoder_Encode_Call[T]) RunAndReturn(run func(v T) (string, error)) *MockTranscoder_Encode_Call[T] {
	_c.Call.Return(run)
	return _c
}
